### ISSUE TITLE
Epic: 사용자는 스크립트에 N회 녹음할 수 있다.

### ISSUE THREAD

**Issue by sigridjineth** [DeliverBle/deliverble-backend-nestjs#90]
## Story
1. 사용자는 1개의 스크립트 당 N개 녹음 파일을 업로드할 수 있다.
2. 사용자는 1개의 스크립트 당 N개의 녹음 파일 정보를 조회할 수 있다.
3. 사용자는 1개의 스크립트에 올라간 임의의 녹음 파일을 다운로드 받을 수 있다.
4. 사용자는 1개의 스크립트에 올라간 임의의 녹음 파일을 삭제할 수 있다.
5. 사용자는 1개의 녹음 파일에 대한 메타데이터(이름)을 변경할 수 있다.

**Comment by beer-2000** [comment]
너무 좋습니다!
기능 정확히 명세되어있네요. 👍👍

다만 기획단 기능 명세에
'녹음 저장 시 이름 변경 가능'이라는 내용이 있어
참고차 공유드립니다.
![image](https://user-images.githubusercontent.com/97939198/200475647-a5f5c584-3914-48e5-8f50-8306f960a57a.jpeg)

(기획단 기능 명세 페이지 링크👇)
https://www.notion.so/bd54bb7379774e288a25c4ecaea00121

**Comment by sigridjineth** [comment]
@horsehair 스토리 5번에서 구현하면 될 것 같은데요. 일단 스토리 1번이 구현되면 나머지의 구현 난이도 및 scope가 크지는 않아서 스토리 5번을 아직 작성하지는 않았습니다.
> 5. 사용자는 1개의 녹음 파일에 대한 메타데이터(이름)을 변경할 수 있다.
